# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161028_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='/images'),
        ),
        migrations.AddField(
            model_name='album',
            name='geo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Geo'),
            preserve_default=False,
        ),
    ]
