# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161105_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
